encoder: SenseVoiceEncoderSmall
encoder_conf:
  output_size: 512
  attention_heads: 4
  linear_units: 2048
  num_blocks: 50
  tp_blocks: 20
  dropout_rate: 0.1
  positional_dropout_rate: 0.1
  attention_dropout_rate: 0.1
  input_layer: pe
  pos_enc_class: SinusoidalPositionEncoder
  normalize_before: true
  kernel_size: 11
  sanm_shfit: 0
  selfattention_layer_type: sanm
model: SenseVoiceSmall
model_conf:
  length_normalized_loss: true
  sos: 1
  eos: 2
  ignore_id: -1
tokenizer: SentencepiecesTokenizer
tokenizer_conf:
  bpemodel: /home/ericyeh/.cache/modelscope/hub/models/iic/SenseVoiceSmall/chn_jpn_yue_eng_ko_spectok.bpe.model
  unk_symbol: <unk>
  split_with_space: true
frontend: WavFrontend
frontend_conf:
  fs: 16000
  window: hamming
  n_mels: 80
  frame_length: 25
  frame_shift: 10
  lfr_m: 7
  lfr_n: 6
  cmvn_file: /home/ericyeh/.cache/modelscope/hub/models/iic/SenseVoiceSmall/am.mvn
dataset: SenseVoiceCTCDataset
dataset_conf:
  index_ds: IndexDSJsonl
  batch_sampler: BatchSampler
  data_split_num: 1
  batch_type: length
  batch_size: 2
  max_token_length: 2048
  min_token_length: 60
  max_source_length: 2000
  min_source_length: 60
  max_target_length: 200
  min_target_length: 0
  shuffle: true
  num_workers: 4
  sos: 1
  eos: 2
  IndexDSJsonl: IndexDSJsonl
  retry: 20
  frontend_conf:
    fs: 16000
train_conf:
  accum_grad: 4
  grad_clip: 3.0
  max_epoch: 15
  keep_nbest_models: 5
  avg_nbest_model: 5
  log_interval: 50
  resume: true
  validate_interval: 500
  save_checkpoint_interval: 500
  use_fp16: false
  find_unused_parameters: false
optim: adam
optim_conf:
  lr: 1.0e-05
  weight_decay: 0.05
  eps: 1.0e-08
  betas:
  - 0.9
  - 0.999
scheduler: warmuplr
scheduler_conf:
  warmup_steps: 500
specaug: SpecAugLFR
specaug_conf:
  apply_time_warp: false
  time_warp_window: 5
  time_warp_mode: bicubic
  apply_freq_mask: true
  freq_mask_width_range:
  - 0
  - 30
  lfr_rate: 6
  num_freq_mask: 1
  apply_time_mask: true
  time_mask_width_range:
  - 0
  - 12
  num_time_mask: 1
init_param: /home/ericyeh/.cache/modelscope/hub/models/iic/SenseVoiceSmall/model.pt
config: /home/ericyeh/.cache/modelscope/hub/models/iic/SenseVoiceSmall/config.yaml
is_training: true
model_dir: ./models/iic/SenseVoiceSmall
device: cpu
cudnn_enabled: false
cudnn_benchmark: false
train_data_set_list: ./data/processed/train.jsonl
valid_data_set_list: ./data/processed/dev.jsonl
output_dir: ./checkpoints/sensevoice_zh_combined_v2
seed: 42
model_path: /home/ericyeh/.cache/modelscope/hub/models/iic/SenseVoiceSmall
